[project]
name = "mulle-js-build"
version = "0.1.0"
description = "Build scripts for the mulle.js project"
authors = [
    { name = "Anders Birkenes", email = "datagutten@datagutten.net" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow",
    "pytexturepacker (>=1.2.1,<2.0.0)",
    "pydub (>=0.25.1,<0.26.0)",
    "audioop-lts (>=0.2.1,<0.3.0); python_version >= '3.13'",
    "pycdlib (>=1.21.0,<2)",
    "gitpython (>=3.1.44,<4.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "lxml (>=6.1.1,<7.0.0)",
    "shockwaveparser @ git+https://github.com/datagutten/ShockwaveParser.git"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
